name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      ngrok_auth_token:
        description: 'Ngrok Auth Token'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip -DestinationPath .

    - name: Set NGROK_AUTH_TOKEN
      run: echo "NGROK_AUTH_TOKEN=${{ github.event.inputs.ngrok_auth_token }}" >> $GITHUB_ENV
    - name: Debug NGROK_AUTH_TOKEN
      run: echo $Env:NGROK_AUTH_TOKEN

    - name: Authenticate ngrok
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ env.NGROK_AUTH_TOKEN }}

    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Firewall Rule for RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable User Authentication for RDP
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Create or Update Local User
      shell: pwsh
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASS: ${{ secrets.PASS }}
      run: |
        New-LocalUser -Name "$Env:USERNAME" -Password (ConvertTo-SecureString -AsPlainText "$Env:PASS" -Force) -ErrorAction SilentlyContinue
        Set-LocalUser -Name "$Env:USERNAME" -Password (ConvertTo-SecureString -AsPlainText "$Env:PASS" -Force)
        Add-LocalGroupMember -Group "Administrators" -Member "$Env:USERNAME"

    - name: Create ngrok Tunnel
      run: .\ngrok.exe tcp 3389 --region=us-cal-1
    - name: Download file zip
      run: Invoke-WebRequest https://github.com/khoantdtdc/FANZYA/raw/main/.github/workflows/Chuotbach.zip -OutFile Chuotbach.zip
           copy Chuotbach.zip D:\Chuotbach.zip
           Expand-Archive -Path "D:\Chuotbach.zip" -DestinationPath "D:\Chuotbach"
    - name: Run executable
      run: D:\Chuotbach\Chuotbach.exe
